data:
  target: dataset.data_module.DataModule
  params:
    # Path to training set configuration file.
    train_config: configs/dataset/general_deg_realesrgan_train.yaml
    # Path to validation set configuration file.
    val_config: 

model:
  # You can set learning rate in the following configuration file.
  config: configs/model/cldm_v21.yaml
  # Path to the checkpoints or weights you want to resume. At the begining, 
  # this should be set to the initial weights created by scripts/make_init_weight.py.
  resume: checkpoints/*

lightning:
  seed: 231
  
  trainer:
    accelerator: ddp
    precision: 32
    # Indices of GPUs used for training.[0, 1, 2, 3] [4, 5, 6, 7]
    gpus: [1, 5, 6, 7]
    # Path to save logs and checkpoints.
    default_root_dir: 
    # Max number of training steps (batches).
    max_steps: 50001
    # Validation frequency in terms of training steps.
    val_check_interval: 10
    log_every_n_steps: 50
    # Accumulate gradients from multiple batches so as to increase batch size.
    accumulate_grad_batches: 1
  
  callbacks:
    - target: model.callbacks.ImageLogger
      params:
        # Log frequency of image logger.
        log_every_n_steps: 5000
        max_images_each_step: 4
        log_images_kwargs: ~

    - target: model.callbacks.ModelCheckpoint
      params:
        # Frequency of saving checkpoints. 5000
        every_n_train_steps: 5000
        save_top_k: -1
        filename: "{step}"
